apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Install early
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.0 # Use current version
    helm:
      valueFiles:
      - $values/2-App-Setup/argocd/apps/values/cert-manager.yml
      values:
        crds:
          enabled: true
  - repoURL: https://github.com/thabich/kubernetes-dev-environment.git
    targetRevision: feature/setup # Use current version
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true # Critical for CRDs
      - CreateNamespace=true
