apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-90" # Install early
spec:
  project: default
  sources:
  - repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: v1.18.3
    helm:
      valueFiles:
      - $values/2-App-Setup/argocd/apps/values/harbor.yml
  - repoURL: https://github.com/thabich/kubernetes-dev-environment.git
    targetRevision: feature/setup
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true # Critical for CRDs
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 20
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 20m

  ignoreDifferences:
    - kind: Deployment
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
        - /spec/template/metadata/annotations/checksum~1secret-core
        - /spec/template/metadata/annotations/checksum~1secret-jobservice
        - /spec/template/metadata/annotations/checksum~1config
    - kind: StatefulSet
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
        - /spec/template/metadata/annotations/checksum~1config
    - kind: Secret
      group: ""
      jsonPointers:
        - /data