- name: Add apt repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    uris: "{{ item.repo }}"
    signed_by: "{{ item.key | default(omit) }}" 
    components: "{{ item.components | default('stable') }}"
    suites: "{{ item.suites | default(ansible_facts['distribution_release']) }}"
    state: present
  with_items: "{{ packages_apt_repositories + packages_extra_apt_repositories }}"

- name: Install packages
  ansible.builtin.apt:
    update_cache: yes
    pkg: "{{ packages_default_packages + packages_extra_packages }}"
    state: present

- name: Remove packages
  ansible.builtin.apt:
    update_cache: no
    pkg: "{{ packages_default_remove_packages + packages_extra_remove_packages }}"
    state: absent

- name: Hold packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: "{{ packages_default_hold_packages + packages_extra_hold_packages }}"