---

- name: reboot
  ansible.builtin.reboot:

- name: Enable dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq.service
    enabled: true
    state: restarted

- name: NetPlan Apply
  ansible.builtin.command:
    cmd: "netplan apply"

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted

- name: Regather facts
  ansible.builtin.setup:
    gather_subset:
    - network
