- name: Check if /dev/sdb exists
  ansible.builtin.stat:
    path: /dev/sdb
  register: disk_stat

- name: Create filesystem if not present
  become: true
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdb
  when: disk_stat.stat.exists

- name: Create mountpoint
  become: true
  ansible.builtin.file:
    path: /exports
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Mount persistent disk
  become: true
  ansible.builtin.mount:
    path: /exports
    src: /dev/sdb
    fstype: ext4
    state: mounted

- name: Ensure fstab entry is present
  become: true
  ansible.builtin.mount:
    path: /exports
    src: /dev/sdb
    fstype: ext4
    opts: defaults
    state: present
  notify: Systemd daemon reload

- name: Install binaries
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    -  nfs-kernel-server

- name: Write exports
  become: true
  ansible.builtin.template:
    dest: "/etc/exports"
    src: "exports.j2"
    owner: root
    group: root
    mode: "0644"
  notify:
  - Enable exports
  - Restart nfs-server

- name: Enable nfs-server
  become: true
  ansible.builtin.systemd:
    name: nfs-server
    state: started
    enabled: true
