- name: Add argo helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install argo-cd
  kubernetes.core.helm:
    name: argocd
    release_namespace: argo-cd
    chart_ref: argo/argo-cd
    create_namespace: true
    values: "{{ lookup('file', 'values.yml') | from_yaml }}"

- name: Install Argo CLI
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    mode: "0755"

- name: Autocompletion
  become: true
  ansible.builtin.lineinfile:
    path: "/home/{{ argocd_admin_user }}/.bashrc"
    line: "source <(argocd completion bash)" 