- name: Add argo helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
    binary_path: "{{ argocd_helm_binary }}"

- name: Install argo-cd
  kubernetes.core.helm:
    name: argocd
    release_namespace: argocd
    chart_ref: argo/argo-cd
    create_namespace: true
    values: "{{ lookup('file', 'values.yml') | from_yaml }}"
    binary_path: "{{ argocd_helm_binary }}"

- name: Apply App-of-Apps manifest
  kubernetes.core.k8s:
    state: present
    namespace: argocd
    definition: "{{ lookup('file', 'app-of-apps.yml') }}"

- name: ArgoCD HTTProute
  kubernetes.core.k8s:
    state: present
    namespace: argocd
    template: httproute.yml.j2
  when: argocd_use_gateway_api|bool


- name: Install Argo CLI
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    mode: "0755"
  notify: Autocompletion
