- name: Get user infos
  ansible.builtin.getent:
    database: passwd

- name: Check if we are on a Vagrant node
  ansible.builtin.set_fact:
    is_vagrant: "{{ true if ansible_facts['virtualization_type'] == 'virtualbox' else false }}"
