---
# We are using netplan to simplify setup on Debian and Ubuntu machines
- name: Create Netplan config
  ansible.builtin.template:
    src: netplan.j2
    dest: /etc/netplan/01-ansible.yaml
    mode: "0600"
    validate: "netplan try --timeout 2 --config-file %s"
  notify: NetPlan Apply



# Enable DHCP services on management host.
- name: Create dnsmasq config
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/01-ansible.conf
    mode: "0600"
    validate: 'dnsmasq --test --conf-file=%s'
  when: groups['service'] is defined and inventory_hostname in  groups['service']
  notify: Enable dnsmasq


- name: Enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: started

- name: Enable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    state: started

# remove and disable ifupdown components in case they exist
- name: Delete /etc/network/interfaces
  ansible.builtin.file:
    path: /etc/network/interfaces
    state: absent

- name: Disable networking
  ansible.builtin.systemd:
    name: networking
    enabled: false
    state: stopped
  notify: "reboot"
  ignore_errors: true

- name: Remove legacy packages
  ansible.builtin.apt:
    update_cache: no
    pkg: 
    - ifupdown
    - dhcpcd-base
    state: absent
  