---
- name: Create user
  ansible.builtin.user:
    name: "{{ common_admin_user }}"
    shell: /bin/bash

- name: Add ssh_authorized_keys
  ansible.posix.authorized_key:
    user: "{{ common_admin_user }}"
    key: "{{ lookup('file', 'public_keys/admin.pub') }}"

- name: Add sudo permissions
  community.general.sudoers:
    name: "{{ common_admin_user }}"
    user: "{{ common_admin_user }}"
    commands: ALL
    runas: ALL

- name: Lock  password for vagrant user
  ansible.builtin.user:
    name: vagrant
    password_lock: true