- hosts: all
  name: Deploy base system
  become: true
  roles:
    - role: common
      tags: [common]
   
- hosts: nodes,controlplane
  name: Deploy Kubernetes
  become: true
  roles:
    - role: kubernetes
      tags: [kubernetes]

- hosts: service
  run_once: true
  name: Deploy Service Host
  become: false
  roles:
    - role: helm
      tags: [helm]
    - role: cilium
      tags: [cilium]
    - role: python
      tags: [python]
    - role: argocd
      tags: [argocd]
    - role: squid
      tags: [squid]
    - role: shellinabox
      tags: [shellinabox]
    - role: external-access
      tags: [external-access]
    - role: sealed-secrets
      tags: [sealed-secrets]
