- hosts: all
  name: Deploy base system
  become: true
  roles:
    - role: common
      tags: [common]
   
- hosts: nodes,controlplane
  name: Deploy Kubernetes
  become: true
  roles:
    - role: kubernetes
      tags: [kubernetes]

- hosts: service
  run_once: true
  name: Deploy Kubernetes
  become: false
  roles:
    - role: helm
      tags: [helm]
    - role: cilium
      tags: [cilium]
    - role: argocd
      tags: [argocd]