- hosts: service
  force_handlers: true
  name: Deploy DHCP service
  become: true
  roles:
    - role: dnsmasq
      tags: [dnsmasq]
  any_errors_fatal: true

- hosts: all
  force_handlers: true
  name: Deploy base system
  become: true
  roles:
    - role: common
      tags: [common]
    - role: users
      tags: [users]
    - role: firewall
      tags: [firewall]
    - role: network
      tags: [network]
    - role: packages
      tags: [packages]
  any_errors_fatal: true

- hosts: kubernetes
  force_handlers: true
  name: Deploy Kubernetes 
  become: true
  roles:
    - role: kubernetes
      tags: [kubernetes]
  any_errors_fatal: true

- hosts: nfs-server
  force_handlers: true
  name: Deploy Service Host
  roles:
    - role: nfs-server
      tags: [nfs-server]
  any_errors_fatal: true

- hosts: service
  force_handlers: true
  name: Deploy Kubernetes additional base 
  roles:
    - role: kubernetes
      tags: [kubernetes]
    - role: helm
      tags: [helm]
    - role: cilium
      tags: [cilium]
  any_errors_fatal: true

- hosts: service
  force_handlers: true
  run_once: true
  name: Deploy GitOps
  become: false
  roles:
    - role: argocd
      tags: [argocd]

- hosts: service
  force_handlers: true
  run_once: true
  name: Deploy Service Host
  roles:
    - role: python
      tags: [python]
    - role: git
      tags: [git]
    - role: squid
      tags: [squid]
  
- hosts: service
  force_handlers: true
  run_once: true
  name: Deploy additional Kubernetes services
  roles:
    - role: external-access
      tags: [external-access]
    - role: sealed-secrets
      tags: [sealed-secrets]
    - role: tekton-cli
      tags: [tekton-cli]

# replaced by Wetty via ArgoCD for better Copy and Paste capabilities
#    - role: shellinabox
#      tags: [shellinabox]