common_extra_packages:
- git
- kubectl
- dnsmasq
- python3-kubernetes
- python3-yaml
- python3-packaging
- python3-virtualenv
- jq

argocd_version: v3.3.6

common_dns_cnames:
- target: manager.k8s.findichgut.net
  fqdn: shell.k8s.findichgut.net


git_repositories:
- repo: https://thabich:{{ git_pat.courses }}@github.com/thabich/courses.git
  dest: "/home/{{ admin_user }}/checkouts/"
  user: "{{ admin_user }}"