common_extra_packages:
- git
- kubectl
- dnsmasq
- python3-kubernetes
- python3-yaml
#- tektoncd-cli

argocd_version: v3.3.6

# common_extra_apt_repositories:
# - name: tekton
#   repo: http://ppa.launchpad.net/tektoncd/cli/ubuntu
#   suites: eoan
#   components: main
#   key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa40e52296e4cf9f90dd1e3bb3efe0e0a2f2f60aa