network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: false
      dhcp6: false
      addresses: [10.0.2.15/24]
      routes:
        # Lokale Route für das Subnetz in Tabelle 100
        - to: default
          via: 10.0.2.2
          table: 100
          on-link: true
      routing-policy:
        - from: 10.0.2.15/32
          table: 100