apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: Helm Chart aus offiziellem Repo
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 15.0.0

    # Source 2: Values aus eigenem Git Repo
    - repoURL: https://github.com/thabich/kubernetes-dev-environment.git
      targetRevision: feature/setup
      path: 1-App-Setup
      helm:
        valueFiles:
          - testvalues.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
