common_apt_repositories: []
common_extra_apt_repositories: []
common_admin_user: vmadm
common_default_packages: []
common_extra_packages: []
common_default_remove_packages: []
common_extra_remove_packages: []
common_default_hold_packages: []
common_extra_hold_packages: []
common_domain: "{{ domain }}"