common_apt_repositories: []
common_extra_apt_repositories: []
common_admin_user: "{{ admin_user | default('vmadm') }}"
common_default_packages: []
common_extra_packages: []
common_default_remove_packages: []
common_extra_remove_packages: []
common_default_hold_packages: []
common_extra_hold_packages: []
common_domain: "{{ domain }}"

common_internal_network: "{{ internal_network | default('10.0.3.0/24') }}"
common_dhcp_range_start: "{{ common_internal_network | ansible.utils.ipaddr('5') | ansible.utils.ipaddr('address')  }}"
common_dhcp_range_end: "{{ common_internal_network | ansible.utils.ipaddr('-2') | ansible.utils.ipaddr('address') }}"
common_dhcp_lease_time: "1h"
common_dhcp_interface: "enp0s9" 
common_service_host_ip: "{{ common_internal_network | ansible.utils.ipaddr('3') }}"
common_default_gateway: "{{ common_internal_network | ansible.utils.ipaddr('2') | ansible.utils.ipaddr('address') }}"

common_dns_host_records: []
common_dns_cnames: []
common_upstream_dns: "8.8.8.8"