- name: Create CRDs for Gateway API
  vars:
    base_url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ cilium_gateway_api_version }}/config/crd
  kubernetes.core.k8s:
    state: present
    src: "{{ base_url }}/{{ item }}"
  loop:
    - standard/gateway.networking.k8s.io_gatewayclasses.yaml
    - standard/gateway.networking.k8s.io_gateways.yaml
    - standard/gateway.networking.k8s.io_grpcroutes.yaml
    - standard/gateway.networking.k8s.io_httproutes.yaml
    - standard/gateway.networking.k8s.io_referencegrants.yaml
    - standard/gateway.networking.k8s.io_backendtlspolicies.yaml
    - experimental/gateway.networking.k8s.io_tlsroutes.yaml
  when: cilium_use_gateway_api|bool

- name: Add cilium helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    binary_path: "{{ cilium_helm_binary }}"

- name: Install cilium
  kubernetes.core.helm:
    name: cilium
    release_namespace: kube-system
    chart_version: "{{ cilium_version }}"
    chart_ref: cilium/cilium
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
    binary_path: "{{ cilium_helm_binary }}"
  notify: Wait for Cilium to come up


- name: Install Cilium CLI
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify: Autocompletion


- name: Create IP pool and policy
  kubernetes.core.k8s:
    state: present
    template: 'lb-ip-pool.yml.j2'
  when: cilium_l2_announcements|bool

- name: Create Central Gateway
  kubernetes.core.k8s:
    state: present
    template: 'gateway.yml.j2'
  when: cilium_use_gateway_api|bool