# Install Sealed Secrets in case it's Ansible managed, otherwise only install CLI
- name: Add sealed secrets helm repo
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: https://bitnami-labs.github.io/sealed-secrets
    binary_path: "{{ sealed_secrets_helm_binary }}"
  when: sealed_secrets_ansible_managed|bool

- name: Install sealed-secrets
  kubernetes.core.helm:
    name: sealed-secrets
    release_namespace: kube-system
    chart_ref: sealed-secrets/sealed-secrets
    chart_version: "{{ sealed_secrets_chart_version }}"
  when: sealed_secrets_ansible_managed|bool


- name: Install kubeseal
  ansible.builtin.command:
    cmd: bash
    stdin: "{{ lookup('file', 'kubeseal-install.sh') }}"
  retries: 5
  delay: 20

- name: Restore sealed secret
  ansible.builtin.command:
    cmd: "kubectl apply -f -"
    stdin: "{{ lookup('file', 'sealed-secrets-secret.vault') }}"
  register: apply_seal_secret
  changed_when: '"unchanged" not in apply_seal_secret.stdout'
  no_log: "{{ sealed_secrets_no_log |default(true) }}"

- name: Restart Pod to activate the new key
  kubernetes.core.k8s:
    api_version: v1
    namespace: kube-system
    kind: Pod
    delete_all: true
    state: absent
    label_selectors:
      - app.kubernetes.io/name=sealed-secrets