- name: Create IP pool and policy
  kubernetes.core.k8s:
    state: present
    template: 'lb-ip-pool.yml.j2'

- name: Create Central Gateway
  kubernetes.core.k8s:
    state: present
    template: 'gateway.yml.j2'

- name: Get IP of Gateway
  ansible.builtin.command:
    cmd: "kubectl get gateway -n kube-system central -o jsonpath='{ .status.addresses[0].value }'"
  register: gateway_ip

- name: Set wildcard DNS record for gateway
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/03-ansible-dns.conf
    create: true
    line: "address=/{{ external_access_domain }}/{{ gateway_ip.stdout}}"
    regexp: "^address=/{{ external_access_domain | regex_escape }}/"
  notify: Restart dnsmasq
