- name: Generate Cluster    
  vars:
    kubernetes_kubeadm_extra: >-
      {% if not kubernetes_use_kube_proxy|bool %}"--skip-phases=addon/kube-proxy"{% endif %}
  ansible.builtin.command:
    cmd: > 
      kubeadm init --apiserver-advertise-address={{ ansible_facts[kubernetes_interface]['ipv4']['address'] }} 
      --apiserver-cert-extra-sans="{{ ansible_facts['hostname'] }},{{ ansible_facts['fqdn'] }},{{ ansible_facts[kubernetes_interface]['ipv4']['address'] }}"
      --control-plane-endpoint="{{ ansible_facts['fqdn'] }}"  
      --node-name "{{ inventory_hostname_short }}" 
      --pod-network-cidr={{ kubernetes_pod_network_cidr }}
      {{ kubernetes_kubeadm_extra }}
    creates: /etc/kubernetes/admin.conf