- name: Create .kube directory for vagrant and admin user
  delegate_to: "{{ system }}"
  ansible.builtin.file:
    path: /home/{{ item }}/.kube
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0700"
  with_items:
  - vagrant
  - "{{ kubernetes_admin_user }}"

- name: Get Kubernetes config
  ansible.builtin.slurp:
    src: /etc/kubernetes/admin.conf
  register: kubeconfig

- name: Write kubernetes config for vagrant
  delegate_to: "{{ system }}"
  delegate_facts: true
  ansible.builtin.copy:
    dest: "/home/{{ item }}/.kube/config"
    content: "{{ kubeconfig['content'] | b64decode }}"
    mode: "0600"
    owner: "{{ item }}"
    group: "{{ item }}"
    force: false
  with_items:
  - vagrant
  - "{{ kubernetes_admin_user }}"