# General setup, like containerd packages
- name: Base Setup
  ansible.builtin.include_tasks:
    file: base_setup.yml
  when: kubernetes_role in ['controlplane', 'node']

# Create the cluster
- name: Setup Cluster
  ansible.builtin.include_tasks:
    file: controlplane.yml
  when: kubernetes_role == 'controlplane'

# Join the nodes
- name: Setup nodes
  ansible.builtin.include_tasks:
    file: node.yml
  when: kubernetes_role == 'node'

# Management tasks, e.g. write kubeconfig
- name: Setup kubernetes_management
  ansible.builtin.include_tasks:
    file: management.yml
  when: kubernetes_role == 'management'