apiVersion: v1
kind: Namespace
metadata:
  name: cluster-mgmt
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: dev-test
    cni: cilium
  name: dev-test
  namespace: cluster-mgmt
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: dev-test-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ProxmoxCluster
    name: dev-test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: dev-test
  name: dev-test
  namespace: cluster-mgmt
spec:
  allowedNodes:
  - pve01
  controlPlaneEndpoint:
    host: 10.0.4.10
    port: 6443
  dnsServers:
  - 8.8.8.8
  - 8.8.4.4
  ipv4Config:
    addresses:
    - 10.0.4.11-10.0.4.50
    gateway: 10.0.4.1
    prefix: 24
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: dev-test-control-plane
  namespace: cluster-mgmt
spec:
  kubeadmConfigSpec:
    files:
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
          - args:
            - manager
            env:
            - name: cp_enable
              value: "true"
            - name: vip_interface
              value: ""
            - name: address
              value: 10.0.4.10
            - name: port
              value: "6443"
            - name: vip_arp
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            image: ghcr.io/kube-vip/kube-vip:v0.7.1
            imagePullPolicy: IfNotPresent
            name: kube-vip
            resources: {}
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - NET_RAW
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostAliases:
          - hostnames:
            - localhost
            - kubernetes
            ip: 127.0.0.1
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/kubernetes/admin.conf
              type: FileOrCreate
            name: kubeconfig
        status: {}
      owner: root:root
      path: /etc/kubernetes/manifests/kube-vip.yaml
    - content: |
        #!/bin/bash

        # Copyright 2020 The Kubernetes Authors.
        #
        # Licensed under the Apache License, Version 2.0 (the "License");
        # you may not use this file except in compliance with the License.
        # You may obtain a copy of the License at
        #
        #     http://www.apache.org/licenses/LICENSE-2.0
        #
        # Unless required by applicable law or agreed to in writing, software
        # distributed under the License is distributed on an "AS IS" BASIS,
        # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        # See the License for the specific language governing permissions and
        # limitations under the License.

        set -e

        # Configure the workaround required for kubeadm init with kube-vip:
        # xref: https://github.com/kube-vip/kube-vip/issues/684

        # Nothing to do for kubernetes < v1.29
        KUBEADM_MINOR="$(kubeadm version -o short | cut -d '.' -f 2)"
        if [[ "$KUBEADM_MINOR" -lt "29" ]]; then
          exit 0
        fi

        IS_KUBEADM_INIT="false"

        # cloud-init kubeadm init
        if [[ -f /run/kubeadm/kubeadm.yaml ]]; then
          IS_KUBEADM_INIT="true"
        fi

        # ignition kubeadm init
        if [[ -f /etc/kubeadm.sh ]] && grep -q -e "kubeadm init" /etc/kubeadm.sh; then
          IS_KUBEADM_INIT="true"
        fi

        if [[ "$IS_KUBEADM_INIT" == "true" ]]; then
          sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' \
            /etc/kubernetes/manifests/kube-vip.yaml
        fi
      owner: root:root
      path: /etc/kube-vip-prepare.sh
      permissions: "0700"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: provider-id
          value: proxmox://'{{ ds.meta_data.instance_id }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: provider-id
          value: proxmox://'{{ ds.meta_data.instance_id }}'
    preKubeadmCommands:
    - /etc/kube-vip-prepare.sh
    users:
    - name: root
      sshAuthorizedKeys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOt4g4teitL/34mQTZdnKaI4NfRYYa9Z6oX2dycla0q9
        habich@THA-HP01
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ProxmoxMachineTemplate
        name: dev-test-control-plane
  replicas: 1
  version: v1.35.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxMachineTemplate
metadata:
  name: dev-test-control-plane
  namespace: cluster-mgmt
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 30
#      format: qcow2
      full: false
      memoryMiB: 2048
      network:
        networkDevices:
        - bridge: hznet
          model: virtio
          name: net0
      numCores: 3
      numSockets: 1
      sourceNode: pve01
      templateID: 9001
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: dev-test
  name: dev-test-workers
  namespace: cluster-mgmt
spec:
  clusterName: dev-test
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: dev-test
        node-role.kubernetes.io/node: ""
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: dev-test-worker
      clusterName: dev-test
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ProxmoxMachineTemplate
        name: dev-test-worker
      version: v1.35.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxMachineTemplate
metadata:
  name: dev-test-worker
  namespace: cluster-mgmt
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 30
      full: false
      memoryMiB: 2048
      network:
        networkDevices:
        - bridge: hznet
          model: virtio
          name: net0
      numCores: 2
      numSockets: 1
      sourceNode: pve01
      templateID: 9001
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: dev-test-worker
  namespace: cluster-mgmt
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
          - name: provider-id
            value: proxmox://'{{ ds.meta_data.instance_id }}'
      users:
      - name: root
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOt4g4teitL/34mQTZdnKaI4NfRYYa9Z6oX2dycla0q9
          habich@THA-HP01
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: dev-test
  name: dev-test-crs-0
  namespace: cluster-mgmt
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: dev-test
      cni: cilium
  resources:
  - kind: ConfigMap
    name: cilium
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: dev-test-worker-unhealthy-5m
  namespace: cluster-mgmt
spec:
  checks:
    nodeStartupTimeoutSeconds: 900
    unhealthyNodeConditions:
    - status: Unknown
      timeoutSeconds: 300
      type: Ready
    - status: "False"
      timeoutSeconds: 300
      type: Ready
  clusterName: dev-test
  remediation:
    triggerIf:
      unhealthyLessThanOrEqualTo: 40%
  selector:
    matchLabels:
      node-role.kubernetes.io/node: ""
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: dev-test-control-plane-unhealthy-5m
  namespace: cluster-mgmt
spec:
  checks:
    unhealthyNodeConditions:
    - status: Unknown
      timeoutSeconds: 300
      type: Ready
    - status: "False"
      timeoutSeconds: 300
      type: Ready
  clusterName: dev-test
  remediation:
    triggerIf:
      unhealthyLessThanOrEqualTo: 100%
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
