IMAGE_NAME = "findichgut.net/debian-cloud"
N = 2

HOSTONLY_ADAPTER_NAME = "VirtualBox Host-Only Ethernet Adapter"
CLOUD_INIT_ISO = 'C:\\checkouts\\kubernetes-dev-environment\\cloud-init-vagrant.iso'
CONTROL_NODE_NAME = "control"
CONTROL_NODE_CPU = 2
CONTROL_NODE_MEMORY = 3072
CONTROL_NODE_DISK_SIZE = "35GB"

SERVICE_NODE_NAME = "manager"
SERVICE_NODE_CPU = 1
SERVICE_NODE_MEMORY = 512
SERVICE_NODE_DISK_SIZE = "35GB"
SERVICE_NODE_MAC = "080027B9AD7E" # static mac for dhcp  reservation
SERVICE_NODE_PERSISTENT_DISK = 'C:\\checkouts\\kubernetes-dev-environment\\data\\persistent-data.vdi'
NODE_NAME_PREFIX = "node"
NODE_CPU = 1
NODE_MEMORY = 2048
NODE_DISK_SIZE = "35GB"

DOMAIN = "k8s.findichgut.net"


def ansible_provision(node)
    node.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.groups = {
            "kubernetes:children" => ["controlplane", "nodes"],
            "controlplane" => [CONTROL_NODE_NAME],
            "nodes" => (1..N).map { |i| "%s%02d" % [NODE_NAME_PREFIX, i] },
            "service" => [SERVICE_NODE_NAME]
        }
        ansible.tags = "all,never"
        ansible.limit = "all"
        ansible.raw_arguments = ["-e", "ansible_ssh_pipelining=True"]
        ansible.ask_vault_pass = true
    end
end


Vagrant.configure("2") do |config|
    config.vm.box = IMAGE_NAME
    config.vm.provider "virtualbox" do |v|
        v.customize ["storageattach", :id,
      "--storagectl", "IDE",
      "--port", 1,
      "--device", 0,
      "--type", "dvddrive",
      "--medium", CLOUD_INIT_ISO ]
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nictype2", "virtio"]
      v.customize ["modifyvm", :id, "--nictype3", "virtio"]
    end
    # Cloud-Init Provisioner aktivieren
    # Vagrant bug, needs fix
    # config.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "cloud-init.yml"

    config.vm.define CONTROL_NODE_NAME do |master|
        master.vm.disk :disk, size: CONTROL_NODE_DISK_SIZE, primary: true
        master.vm.hostname = CONTROL_NODE_NAME + "." + DOMAIN
        master.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--nic3", "intnet"]
            v.customize ["modifyvm", :id, "--intnet3", "k8sNetwork"]
            v.memory = CONTROL_NODE_MEMORY
            v.cpus = CONTROL_NODE_CPU
            v.name = CONTROL_NODE_NAME
            
        end
    end

    (1..N).each do |i|
        config.vm.define "%s%02d" % [NODE_NAME_PREFIX, i]  do |node|
            node.vm.disk :disk, size: NODE_DISK_SIZE, primary: true
            node.vm.hostname = "%s%02d" % [NODE_NAME_PREFIX, i]  + "." + DOMAIN
            node.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--nic3", "intnet"]
                v.customize ["modifyvm", :id, "--intnet3", "k8sNetwork"]
                v.memory = NODE_MEMORY
                v.cpus = NODE_CPU
                v.name = "%s%02d" % [NODE_NAME_PREFIX, i]
            end
        end
    end

    config.vm.define SERVICE_NODE_NAME do |service|
        service.vm.hostname = SERVICE_NODE_NAME + "." + DOMAIN
        service.vm.network "public_network", bridge: "Intel(R) Wi-Fi 7 BE200 320MHz", adapter: 2, :mac => SERVICE_NODE_MAC
        service.vm.disk :disk, size: SERVICE_NODE_DISK_SIZE, primary: true
        service.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--nic3", "intnet"]
            v.customize ["modifyvm", :id, "--intnet3", "k8sNetwork"]
            v.memory = SERVICE_NODE_MEMORY
            v.cpus = SERVICE_NODE_CPU
            v.name = SERVICE_NODE_NAME
            v.customize ["storageattach", :id,
                "--storagectl", "SATA",
                "--port", 1,
                "--device", 0,
                "--type", "hdd",
                "--hotpluggable", "on",
                "--medium", SERVICE_NODE_PERSISTENT_DISK]
        end
        ansible_provision(service)


        # Keep data disk
        service.trigger.before :destroy do |trigger|
            trigger.ruby do |env, machine|
                # Detach the data disk
                machine.provider.driver.execute("storageattach", "#{SERVICE_NODE_NAME}",
                        "--storagectl", "SATA", # Name of your controller
                        "--port", "1",
                        "--device", "0",
                        "--type", "hdd",
                        "--medium", "none")
            end
        end

        # Remove Key from known hosts
        service.trigger.after :destroy do |trigger|
            trigger.run = {
                inline: "ssh-keygen -f '/home/habich/.ssh/known_hosts' -R #{SERVICE_NODE_NAME}"
            }
        end
    end
end